@startuml Class Diagram 

package main {

    class ActressListElement

    package landing {
        class MainWindow
        class ActressesListModel
        class AccessActressesListThread
    }

    package detail {
        class ActressDetail
        class DetailView
        class DetailViewModel
        class MoviesDataWorker
        class ActressAwardsDataWorker
    }
}

MainWindow o-- DetailView
DetailView o-- ActressDetail
DetailView o-- ActressAwardsDataWorker
DetailView o-- MoviesDataWorker
DetailView o-- DetailViewModel
@enduml