@startuml movies-data-worker-sequence 

MainView -> DetailView: init Content
DetailView -> MoviesDataWorker: fetch movie data
MoviesDataWorker --> DetailView: send rating, awards, genre and table index
DetailView -> MoviesTable: set rating awards genre
DetailView -> AvRatingLabel: set average rating

@enduml